service: discord-auth
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:service}*"

functions:
  app:
    handler: dist/server.handler
    environment:
      SECRET_KEY: ${ssm:/${self:service}/secret_key}
      JWT_SECRET_KEY: ${ssm:/${self:service}/jwt_secret_key}
      DISCORD_SECRET_KEY: ${ssm:/${self:service}/discord_secret_key}
      DISCORD_CLIENT_ID: ${ssm:/${self:service}/discord_client_id}
      DISCORD_PORT: ${ssm:/${self:service}/discord_port}
      SERVER_URL: ${ssm:/${self:service}/server_url}
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
